### ISSUE TITLE
[Connector Roadmap] Update `meroxa resources list --types` command

### ISSUE THREAD

**Issue by jayjayjpg** [meroxa/cli#596]
As part of the Connector Roadmap feature, we should update the CLI command for listing resource types:

```bash
$ meroxa resources list --types
```

### Current command output (default)

```bash
$ meroxa resources list --types

     TYPES      
================
       postgres 
             s3 
       redshift 
          mysql 
            url 
        mongodb 
  elasticsearch 
    snowflakedb 
       bigquery 
      sqlserver 
          kafka 
 confluentcloud 
         notion 
       cosmosdb 
```

### Current command output (json)

```json
[
	"postgres",
	"s3",
	"redshift",
	"mysql",
	"url",
	"mongodb",
	"elasticsearch",
	"snowflakedb",
	"bigquery",
	"sqlserver",
	"kafka",
	"confluentcloud",
	"notion",
	"cosmosdb"
]
```

### Expected command output

```bash
$ meroxa resources list --types

  Resource Type         |  Release Stage
==================================================================
       postgres          beta
             s3          beta
       redshift          beta
          mysql          beta
            url          beta
        mongodb          beta
  elasticsearch          beta
    snowflakedb          beta
       bigquery          beta
      sqlserver          beta
          kafka          beta
 confluentcloud          beta
         notion          beta
       cosmosdb          beta

View a complete list of available and upcoming Resources in the dashboard: https://dashboard.meroxa.io/resources/new
```

## Technical suggestions

Divide the work into two separate PRs to facilitate internal testing before we're ready to release. For more context, see also [the previous discussion on Slack](https://meroxa.slack.com/archives/C03FL181C3A/p1675098098447159?thread_ts=1675089044.726659&cid=C03FL181C3A)

### First PR

These changes can be merged as soon as possible in the pre-release week:

- [ ] update the util for the resource type list command to parse the new API payload sent from `/v2/resource-types`
- [ ] only return those resources that are in release stage `beta` in the command output
- [ ] add at least one unit test verifying the correct output of the list of `beta` resources
- [ ] create a PR with the aforementioned changes that can already be merged in the pre-release week between January 30 and February 5, so we can do QA on the main branch of the CLI repo

### Second PR

These changes should be merged when we're close to our release:

- [ ] in separate follow-up PR, add the additional follow up message to the end of the command output: `To view a complete list of resources...`
- [ ] add at least one unit test verifying the existence of the follow-up link at the very end of the command output

**Comment by janelletavares** [comment]
https://github.com/meroxa/meroxa-go/pull/156
https://github.com/meroxa/cli/pull/602

**Comment by jayjayjpg** [comment]
@janelletavares Thank you for updating the ticket with the latest design from the implementation doc,  I totally missed this! 🙇🏾‍♀️

**Comment by jayjayjpg** [comment]
@janelletavares @justmisosoup  I just updated the implementation plan and this ticket. with the new resource page url that w had discussed in standup today: https://www.notion.so/Connector-Roadmap-Implementation-Plan-3c3f3be755844f7eac0a56cec81d553b?d=ddb58981c0ed49f5b74bab289ba027d5#251157482d894946a50ed56c5e7f11ee

**Comment by jayjayjpg** [comment]
@janelletavares I updated the technical suggestions for this ticket following our discussion today to make the release of the CLI changes easier, but feel free to adopt, edit or leave as you see fit!

**Comment by justmisosoup** [comment]
My recommendation for output:

```
$ meroxa resources list --types

             NAME                  TYPE          RELEASE STAGE
=========================== ================= ===================
PostgreSQL                  postgres          beta
Amazon S3                   s3                beta
Amazon Redshift             redshift          beta
MySQL                       mysql             beta
HTTP                        url               beta
MongoDB                     mongodb           beta
Elasticsearch               elasticsearch     beta
Snowflake                   snowflakedb       beta
Google BigQuer              bigquery          beta
Microsoft SQL Server        sqlserver         beta
Apache Kafka                kafka             beta
Confluent Cloud             confluentcloud    beta
Notion                      notion            beta
Azure CosmoDB               cosmosdb          beta

View a complete list of available and upcoming Resources in the dashboard: https://dashboard.meroxa.io/resources/new
